---
- name: Set fact project
  tags: neutron
  set_fact:
    project: "{{ item.key }}"
    networks: "{{ item.value|rejectattr('provider_network_name', 'defined')|list }}"
    subnets: "{{ item.value }}"

- name: Create networks
  tags: neutron
  with_items: "{{ networks }}"
  os_network:
    auth: "{{ os_auth[project] }}"
    name: "{{ item.name }}"
    external: False

- name: Create subnets
  tags: neutron
  with_items: "{{ subnets }}"
  os_subnet:
    auth: "{{ os_auth[project] }}"
    name: "{{ item.name ~ '_subnet'}}"
    network_name: "{{ item.name }}"
    allocation_pool_start:  "{{ item.allocation_pool.start }}"
    allocation_pool_end: "{{ item.allocation_pool.end }}"
    cidr: "{{ item.cidr }}"
    dns_nameservers: "{{ item.dns_nameservers|default(omit)}}"
    enable_dhcp: "{{ item.enable_dhcp|default(omit)}}"
    gateway_ip: "{{ item.gateway_ip|default(omit)}}"

- name: Create routerport
  tags: neutron
  with_items: "{{ networks }}"
  when: "{{ item.external_netname is defined }}"
  os_router:
    auth: "{{ os_auth[project] }}"
    # Must be site unique.....
    name: "{{ project ~ '_router_' ~ item.external_netname }}"
    network: "{{ item.external_netname }}"
    interfaces: "{{ item.name ~ '_subnet'}}"
